

test:
  except:
    - tags
  image: registry.gitlab.com/intergral/docker/build-images/python:pybuild_3_protoc
  script:
    - echo "todo"

publish:
  only:
    - tags
  image: registry.gitlab.com/intergral/docker/build-images/python:pybuild_3_protoc
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
